server:
  port: 9301
spring:
  application:
    name: provider
  datasource:
    username: root
    password: 251968840zx
    url: jdbc:mysql://sh-cdb-7rxgx538.sql.tencentcdb.com:59306/demo?autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
data:
  env: "dev-env"
  user:
    username: NaN
    password: NaN
